[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "medication_management"
version = "0.1.0"
description = "Sistema de gestión de medicamentos - Poetry"
authors = ["Matteo Imbrosciano <tuemail@example.com>"]
license = { text = "GPL-3.0-or-later" }

readme = "README.md"
requires-python = ">=3.9"

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
flake8 = "^5.0.0"   # Verificación de Sintaxis
black = "^23.0.0"   # Formateo de código
pytest = "^7.0.0"   # Pruebas

[tasks.check_syntax]
command = "flake8"
args = ["--max-line-length=88"]

[tasks.check_style]
command = "black"
args = ["--check", "--line-length", "88"]

[tasks.format_code]
command = "black"
args = ["--line-length", "88"]

[tasks.test]
command = "pytest"
args = ["--maxfail=5", "--disable-warnings", "--tb=short"]

[tasks.build]
command = "poetry"
args = ["build"]

[tasks.clean]
command = "poetry"
args = ["env", "remove", "python"]

[tasks.full]
dependencies = ["check_syntax", "check_style", "build", "test"]

[tasks.clean-full]
dependencies = ["clean", "full"]