[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "medication_management"
version = "0.1.0"
description = "Sistema de gestión de medicamentos"
readme = "README.md"
license = { text = "GPL-3.0-or-later" }
requires-python = ">=3.9"